# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresql-docker:
    image: postgres
    restart: always
    container_name: postgresql-docker
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
      POSTGRES_USER: ${POSTGRES_PASSWORD:-postgres}
    env_file:
      - ./docker.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin-docker:
    image: openkbs/pgadmin-docker
    build:
      context: ./Dockerfile
    container_name: pgadmin-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./docker.env
    volumes:
      - ./workspace:/home/developer/workspace

